export default [
  {
    id: "218665900",
    name: "Maro mujhe maaro",
    url: "https://i.imgflip.com/3m6ros.jpg",
    box_count: 2,
  },
  {
    id: "21670300",
    name: "Angry Indian Mum",
    url: "https://i.imgflip.com/cwgws.jpg",
    box_count: 2,
  },
  {
    id: "7303431",
    name: "Hairy Indian",
    url: "https://i.imgflip.com/4cjd3.jpg",
    box_count: 2,
  },
  {
    id: "249302504",
    name: "He Ma Mataji",
    url: "https://i.imgflip.com/44ff1k.jpg",
    box_count: 2,
  },
  {
    id: "236376222",
    name: "Shocked dadaji",
    url: "https://i.imgflip.com/3wqd26.jpg",
    box_count: 2,
  },
  {
    id: "231982263",
    name: "It's her choice",
    url: "https://i.imgflip.com/3u46nr.jpg",
    box_count: 2,
  },
  {
    id: "242789521",
    name: "Tarak Mehta",
    url: "https://i.imgflip.com/40jtld.jpg",
    box_count: 2,
  },
  {
    id: "243493201",
    name: "Paise barbad",
    url: "https://i.imgflip.com/40ywk1.png",
    box_count: 2,
  },
  {
    id: "242980981",
    name: "Bahut tez ho gaye ho",
    url: "https://i.imgflip.com/40nxbp.png",
    box_count: 2,
  },
  {
    id: "236076841",
    name: "Abhi maza ayega na bhidu",
    url: "https://i.imgflip.com/3wjy21.jpg",
    box_count: 2,
  },
  {
    id: "247849976",
    name: "Kaisa laga mera mazak",
    url: "https://i.imgflip.com/43ka9k.jpg",
    box_count: 2,
  },
  {
    id: "241223895",
    name: "Control Uday Control",
    url: "https://i.imgflip.com/3zm9jr.jpg",
    box_count: 2,
  },
  {
    id: "231622448",
    name: "Seh lenge thoda",
    url: "https://i.imgflip.com/3twh0w.jpg",
    box_count: 2,
  },
  {
    id: "202272170",
    name: "Tum Bohot Mast Kaam Karta Hai",
    url: "https://i.imgflip.com/3cfe7e.jpg",
    box_count: 2,
  },
  {
    id: "145314852",
    name: "Munna Bhai Zaruri Hai kya",
    url: "https://i.imgflip.com/2eilno.jpg",
    box_count: 2,
  },
  {
    id: "171043005",
    name: "Kehna kya chate ho",
    url: "https://i.imgflip.com/2tu1ml.png",
    box_count: 2,
  },
  {
    id: "139347089",
    name: "Chatur 3 idiots",
    url: "https://i.imgflip.com/2ayowh.jpg",
    box_count: 2,
  },
  {
    id: "155380020",
    name: "This is beyond science",
    url: "https://i.imgflip.com/2kibzo.jpg",
    box_count: 2,
  },
  {
    id: "243287128",
    name: "Bilkul Ricks nahi lene ka",
    url: "https://i.imgflip.com/40uhjs.jpg",
    box_count: 2,
  },
  {
    id: "197572804",
    name: "Maal kidhar hai",
    url: "https://i.imgflip.com/39mo5g.jpg",
    box_count: 2,
  },
  {
    id: "189703558",
    name: "Ye scheme tere liye hai hi nahi",
    url: "https://i.imgflip.com/34y07a.jpg",
    box_count: 2,
  },
  {
    id: "219438619",
    name: "Paisa hi paisa",
    url: "https://i.imgflip.com/3mnbx7.jpg",
    box_count: 2,
  },
  {
    id: "237325726",
    name: "3 Din to bohat kam hai",
    url: "https://i.imgflip.com/3xappa.jpg",
    box_count: 2,
  },
  {
    id: "185780387",
    name: "Khopdi tod saale ka",
    url: "https://i.imgflip.com/32lx2b.png",
    box_count: 2,
  },
  {
    id: "216146025",
    name: "Amit Shah chronology",
    url: "https://i.imgflip.com/3korc9.png",
    box_count: 2,
  },

  {
    id: "113846922",
    name: "Daydreaming Modi",
    url: "https://i.imgflip.com/1vs4ui.jpg",
    box_count: 2,
  },
  {
    id: "243575761",
    name: "Modi Xi Jinping",
    url: "https://i.imgflip.com/410o9d.jpg",
    box_count: 2,
  },
  {
    id: "252418339",
    name: "Modi ji speech",
    url: "https://i.imgflip.com/46a78j.jpg",
    box_count: 2,
  },
  {
    id: "188445986",
    name: "Mere ko to aisa dhak dhak",
    url: "https://i.imgflip.com/3471uq.png",
    box_count: 2,
  },
].reverse();
